{% set name = "simple-term-menu" %}
{% set version = "1.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple-term-menu-{{ version }}.tar.gz
  sha256: be9c5dbd8df12a404b14cd8e95d6fc02d58c60e2555f65ddde41777c487fb3b9

build:
  entry_points:
    - simple-term-menu = simple_term_menu:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - simple_term_menu
  commands:
    - pip check
    - simple-term-menu --help
  requires:
    - pip

about:
  home: https://github.com/IngoMeyer441/simple-term-menu
  summary: A Python package which creates simple interactive menus on the command line.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
