{% set name = "simple-term-menu" %}
{% set version = "1.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9813d36f5749d62d200a5599b1ec88469c71378312adc084c00c00bfbb383893

build:
  entry_points:
    - simple-term-menu = simple_term_menu:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - simple_term_menu
  commands:
    - pip check
    - simple-term-menu --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IngoMeyer441/simple-term-menu
  summary: A Python package which creates simple interactive menus on the command line.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
