{% set name = "simple-term-menu" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa5745abbd5f329383207d759878750da1b103347df2c03174a829789c15efed

build:
  entry_points:
    - simple-term-menu = simple_term_menu:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - simple_term_menu
  commands:
    - pip check
    - simple-term-menu --help
  requires:
    - pip

about:
  home: https://github.com/IngoMeyer441/simple-term-menu
  summary: A Python package which creates simple interactive menus on the command line.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
